[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "universalddns"
version = "0.1.0"
authors = [
  { name="Brett Hoshaw", email="admin@bigcloudnetworking.com" },
]
description = "A universal dynamic DNS client package"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" } # You can specify the license here
keywords = ["ddns", "dynamic", "dns", "cloudflare"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License", # Update if you choose differently
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "httpx",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/universalddns" # Replace
"Bug Tracker" = "https://github.com/yourusername/universalddns/issues" # Replace

[tool.setuptools.packages.find]
where = ["."]